genesis-file="/data/genesis.json"
# Networking
p2p-host="0.0.0.0"
p2p-port=30303
p2p-enabled=true
# IPC configuration

# JSON-RPC
bootnodes=["enode://036e7817aad52ab66c02a8cbdd78995d01be7196403679e37eef9a8441731410012d5cf88a55ffb3573aa86bc6ec549ed1fadb2d53ece5182d2c18d99a2e77a2@10.89.0.2:30303"]

# Node discovery
discovery-enabled=true

rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-cors-origins=["*"]
rpc-http-api=["ETH", "NET", "CLIQUE", "ADMIN", "TRACE", "DEBUG", "TXPOOL", "PERM"]
host-allowlist=["*"]